In [1]:
'''
# E-Commerce Sales Analytics & Customer Satisfaction Prediction

## Phase 2

### Notebook 1

Data Loading and Understanding

Author: Vaishnavi Gavade
'''

'\n# E-Commerce Sales Analytics & Customer Satisfaction Prediction\n\n## Phase 2\n\n### Notebook 1\n\nData Loading and Understanding\n\nAuthor: Vaishnavi Gavade\n'

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

%matplotlib inline

In [3]:
customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")

orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")

order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")

payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")

products = pd.read_csv("../data/raw/olist_products_dataset.csv")

reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")

In [4]:
print("Customers Shape :", customers.shape)

print("Orders Shape :", orders.shape)

print("Order Items Shape :", order_items.shape)

print("Payments Shape :", payments.shape)

print("Products Shape :", products.shape)

print("Reviews Shape :", reviews.shape)

Customers Shape : (99441, 5)
Orders Shape : (99441, 8)
Order Items Shape : (112650, 7)
Payments Shape : (103886, 5)
Products Shape : (32951, 9)
Reviews Shape : (99224, 7)

In [5]:
summary = pd.DataFrame({
    "Dataset": [
        "Customers",
        "Orders",
        "Order Items",
        "Payments",
        "Products",
        "Reviews"
    ],
    "Rows": [
        customers.shape[0],
        orders.shape[0],
        order_items.shape[0],
        payments.shape[0],
        products.shape[0],
        reviews.shape[0]
    ],
    "Columns": [
        customers.shape[1],
        orders.shape[1],
        order_items.shape[1],
        payments.shape[1],
        products.shape[1],
        reviews.shape[1]
    ]
})

summary

       Dataset    Rows  Columns
0    Customers   99441        5
1       Orders   99441        8
2  Order Items  112650        7
3     Payments  103886        5
4     Products   32951        9
5      Reviews   99224        7

In [57]:
print("=" * 70)
print("CUSTOMERS DATASET")
print("=" * 70)

customers.head()

======================================================================
CUSTOMERS DATASET
======================================================================

                        customer_id                customer_unique_id  customer_zip_code_prefix          customer_city customer_state
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0                     14409                 franca             SP
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3                      9790  sao bernardo do campo             SP
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e                      1151              sao paulo             SP
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c                      8775        mogi das cruzes             SP
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066                     13056               campinas             SP

In [58]:
print("=" * 70)
print("ORDERS DATASET")
print("=" * 70)

orders.head()

======================================================================
ORDERS DATASET
======================================================================

                           order_id                       customer_id order_status order_purchase_timestamp    order_approved_at order_delivered_carrier_date order_delivered_customer_date order_estimated_delivery_date
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15          2017-10-04 19:55:00           2017-10-10 21:25:13           2017-10-18 00:00:00
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27          2018-07-26 14:31:00           2018-08-07 15:27:45           2018-08-13 00:00:00
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23          2018-08-08 13:50:00           2018-08-17 18:06:29           2018-09-04 00:00:00
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59          2017-11-22 13:39:59           2017-12-02 00:28:42           2017-12-15 00:00:00
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29          2018-02-14 19:46:34           2018-02-16 18:17:02           2018-02-26 00:00:00

In [59]:
print("=" * 70)
print("ORDER ITEMS DATASET")
print("=" * 70)

order_items.head()

======================================================================
ORDER ITEMS DATASET
======================================================================

                           order_id  order_item_id                        product_id                         seller_id  shipping_limit_date   price  freight_value
0  00010242fe8c5a6d1ba2dd792cb16214              1  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202  2017-09-19 09:45:35   58.90          13.29
1  00018f77f2f0320c557190d7a144bdd3              1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36  2017-05-03 11:05:13  239.90          19.93
2  000229ec398224ef6ca0657da4fc703e              1  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d  2018-01-18 14:48:30  199.00          17.87
3  00024acbcdf0a6daa1e931b038114c75              1  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4  2018-08-15 10:10:18   12.99          12.79
4  00042b26cf59d7ce69dfabb4e55b4fd9              1  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87  2017-02-13 13:57:51  199.90          18.14

In [60]:
print("=" * 70)
print("PAYMENTS DATASET")
print("=" * 70)

payments.head()

======================================================================
PAYMENTS DATASET
======================================================================

                           order_id  payment_sequential payment_type  payment_installments  payment_value
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card                     8          99.33
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card                     1          24.39
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card                     1          65.71
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card                     8         107.78
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card                     2         128.45

In [61]:
print("=" * 70)
print("PRODUCTS DATASET")
print("=" * 70)

products.head()

======================================================================
PRODUCTS DATASET
======================================================================

                         product_id  product_category_name  product_name_lenght  product_description_lenght  product_photos_qty  product_weight_g  product_length_cm  product_height_cm  product_width_cm
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria                 40.0                       287.0                 1.0             225.0               16.0               10.0              14.0
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes                 44.0                       276.0                 1.0            1000.0               30.0               18.0              20.0
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer                 46.0                       250.0                 1.0             154.0               18.0                9.0              15.0
3  cef67bcfe19066a932b7673e239eb23d                  bebes                 27.0                       261.0                 1.0             371.0               26.0                4.0              26.0
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas                 37.0                       402.0                 4.0             625.0               20.0               17.0              13.0

In [62]:
print("=" * 70)
print("REVIEWS DATASET")
print("=" * 70)

reviews.head()

======================================================================
REVIEWS DATASET
======================================================================

                          review_id                          order_id  review_score review_comment_title                             review_comment_message review_creation_date review_answer_timestamp
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb             4                  NaN                                                NaN  2018-01-18 00:00:00     2018-01-18 21:46:59
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33             5                  NaN                                                NaN  2018-03-10 00:00:00     2018-03-11 03:05:13
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b             5                  NaN                                                NaN  2018-02-17 00:00:00     2018-02-18 14:36:24
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b             5                  NaN              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00     2017-04-21 22:02:06
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1             5                  NaN  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00     2018-03-02 10:26:53

In [12]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state'], dtype='object')

In [13]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date'], dtype='object')

In [14]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value'], dtype='object')

In [15]:
payments.columns

Index(['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value'], dtype='object')

In [16]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm'], dtype='object')

In [17]:
reviews.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp'], dtype='object')

In [18]:
customers.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [19]:
orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [20]:
order_items.dtypes

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [21]:
payments.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [22]:
products.dtypes

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [23]:
reviews.dtypes

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

In [55]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [56]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [26]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [27]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [28]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [29]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [30]:
customers.describe(include='all')

                             customer_id                customer_unique_id  customer_zip_code_prefix customer_city customer_state
count                              99441                             99441              99441.000000         99441          99441
unique                             99441                             96096                       NaN          4119             27
top     06b8999e2fba1a1fbc88172c00ba8bc7  8d50f5eadf50201ccdcedfb9e2ac8455                       NaN     sao paulo             SP
freq                                   1                                17                       NaN         15540          41746
mean                                 NaN                               NaN              35137.474583           NaN            NaN
std                                  NaN                               NaN              29797.938996           NaN            NaN
min                                  NaN                               NaN               1003.000000           NaN            NaN
25%                                  NaN                               NaN              11347.000000           NaN            NaN
50%                                  NaN                               NaN              24416.000000           NaN            NaN
75%                                  NaN                               NaN              58900.000000           NaN            NaN
max                                  NaN                               NaN              99990.000000           NaN            NaN

In [31]:
orders.describe(include='all')

                                order_id                       customer_id order_status order_purchase_timestamp    order_approved_at order_delivered_carrier_date order_delivered_customer_date order_estimated_delivery_date
count                              99441                             99441        99441                    99441                99281                        97658                         96476                         99441
unique                             99441                             99441            8                    98875                90733                        81018                         95664                           459
top     e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d    delivered      2018-08-02 12:05:26  2018-02-27 04:31:10          2018-05-09 15:48:00           2018-05-08 19:36:48           2017-12-20 00:00:00
freq                                   1                                 1        96478                        3                    9                           47                             3                           522

In [32]:
order_items.describe(include='all')

                                order_id  order_item_id                        product_id                         seller_id  shipping_limit_date          price  freight_value
count                             112650  112650.000000                            112650                            112650               112650  112650.000000  112650.000000
unique                             98666            NaN                             32951                              3095                93318            NaN            NaN
top     8272b63d03f5f79c56e9e4120aec44ef            NaN  aca2eb7d00ea1a7b8ebd4e68314663af  6560211a19b47992c3666cc44a7e94c0  2017-07-21 18:25:23            NaN            NaN
freq                                  21            NaN                               527                              2033                   21            NaN            NaN
mean                                 NaN       1.197834                               NaN                               NaN                  NaN     120.653739      19.990320
std                                  NaN       0.705124                               NaN                               NaN                  NaN     183.633928      15.806405
min                                  NaN       1.000000                               NaN                               NaN                  NaN       0.850000       0.000000
25%                                  NaN       1.000000                               NaN                               NaN                  NaN      39.900000      13.080000
50%                                  NaN       1.000000                               NaN                               NaN                  NaN      74.990000      16.260000
75%                                  NaN       1.000000                               NaN                               NaN                  NaN     134.900000      21.150000
max                                  NaN      21.000000                               NaN                               NaN                  NaN    6735.000000     409.680000

In [33]:
payments.describe(include='all')

                                order_id  payment_sequential payment_type  payment_installments  payment_value
count                             103886       103886.000000       103886         103886.000000  103886.000000
unique                             99440                 NaN            5                   NaN            NaN
top     fa65dad1b0e818e3ccc5cb0e39231352                 NaN  credit_card                   NaN            NaN
freq                                  29                 NaN        76795                   NaN            NaN
mean                                 NaN            1.092679          NaN              2.853349     154.100380
std                                  NaN            0.706584          NaN              2.687051     217.494064
min                                  NaN            1.000000          NaN              0.000000       0.000000
25%                                  NaN            1.000000          NaN              1.000000      56.790000
50%                                  NaN            1.000000          NaN              1.000000     100.000000
75%                                  NaN            1.000000          NaN              4.000000     171.837500
max                                  NaN           29.000000          NaN             24.000000   13664.080000

In [34]:
products.describe(include='all')

                              product_id product_category_name  product_name_lenght  product_description_lenght  product_photos_qty  product_weight_g  product_length_cm  product_height_cm  product_width_cm
count                              32951                 32341         32341.000000                32341.000000        32341.000000      32949.000000       32949.000000       32949.000000      32949.000000
unique                             32951                    73                  NaN                         NaN                 NaN               NaN                NaN                NaN               NaN
top     1e9e8ef04dbcff4541ed26657ea517e5       cama_mesa_banho                  NaN                         NaN                 NaN               NaN                NaN                NaN               NaN
freq                                   1                  3029                  NaN                         NaN                 NaN               NaN                NaN                NaN               NaN
mean                                 NaN                   NaN            48.476949                  771.495285            2.188986       2276.472488          30.815078          16.937661         23.196728
std                                  NaN                   NaN            10.245741                  635.115225            1.736766       4282.038731          16.914458          13.637554         12.079047
min                                  NaN                   NaN             5.000000                    4.000000            1.000000          0.000000           7.000000           2.000000          6.000000
25%                                  NaN                   NaN            42.000000                  339.000000            1.000000        300.000000          18.000000           8.000000         15.000000
50%                                  NaN                   NaN            51.000000                  595.000000            1.000000        700.000000          25.000000          13.000000         20.000000
75%                                  NaN                   NaN            57.000000                  972.000000            3.000000       1900.000000          38.000000          21.000000         30.000000
max                                  NaN                   NaN            76.000000                 3992.000000           20.000000      40425.000000         105.000000         105.000000        118.000000

In [35]:
reviews.describe(include='all')

                               review_id                          order_id  review_score review_comment_title review_comment_message review_creation_date review_answer_timestamp
count                              99224                             99224  99224.000000                11568                  40977                99224                   99224
unique                             98410                             98673           NaN                 4527                  36159                  636                   98248
top     08528f70f579f0c830189efc523d2182  df56136b8031ecd28e200bb18e6ddb2e           NaN            Recomendo              Muito bom  2017-12-19 00:00:00     2017-06-15 23:21:05
freq                                   3                                 3           NaN                  423                    230                  463                       4
mean                                 NaN                               NaN      4.086421                  NaN                    NaN                  NaN                     NaN
std                                  NaN                               NaN      1.347579                  NaN                    NaN                  NaN                     NaN
min                                  NaN                               NaN      1.000000                  NaN                    NaN                  NaN                     NaN
25%                                  NaN                               NaN      4.000000                  NaN                    NaN                  NaN                     NaN
50%                                  NaN                               NaN      5.000000                  NaN                    NaN                  NaN                     NaN
75%                                  NaN                               NaN      5.000000                  NaN                    NaN                  NaN                     NaN
max                                  NaN                               NaN      5.000000                  NaN                    NaN                  NaN                     NaN

In [36]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [37]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [38]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [39]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [40]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [41]:
reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [42]:
customers.duplicated().sum()

np.int64(0)

In [43]:
orders.duplicated().sum()

np.int64(0)

In [44]:
order_items.duplicated().sum()

np.int64(0)

In [45]:
payments.duplicated().sum()

np.int64(0)

In [46]:
products.duplicated().sum()

np.int64(0)

In [47]:
reviews.duplicated().sum()

np.int64(0)

In [48]:
customers.nunique()

customer_id                 99441
customer_unique_id          96096
customer_zip_code_prefix    14994
customer_city                4119
customer_state                 27
dtype: int64

In [49]:
orders.nunique()

order_id                         99441
customer_id                      99441
order_status                         8
order_purchase_timestamp         98875
order_approved_at                90733
order_delivered_carrier_date     81018
order_delivered_customer_date    95664
order_estimated_delivery_date      459
dtype: int64

In [50]:
order_items.nunique()

order_id               98666
order_item_id             21
product_id             32951
seller_id               3095
shipping_limit_date    93318
price                   5968
freight_value           6999
dtype: int64

In [51]:
payments.nunique()

order_id                99440
payment_sequential         29
payment_type                5
payment_installments       24
payment_value           29077
dtype: int64

In [52]:
products.nunique()

product_id                    32951
product_category_name            73
product_name_lenght              66
product_description_lenght     2960
product_photos_qty               19
product_weight_g               2204
product_length_cm                99
product_height_cm               102
product_width_cm                 95
dtype: int64

In [53]:
reviews.nunique()

review_id                  98410
order_id                   98673
review_score                   5
review_comment_title        4527
review_comment_message     36159
review_creation_date         636
review_answer_timestamp    98248
dtype: int64