# 📓 SQL Analysis

## 🎯 Objective

The objective of this notebook is to analyze the engineered e-commerce dataset using SQL queries. SQL enables efficient data retrieval, filtering, aggregation, and reporting, making it an essential tool for business intelligence and data analysis.

In this notebook, we will answer real-world business questions using SQL and compare the results with the analyses performed in Python and Power BI.

## 📖 Description

After completing feature engineering, the dataset is now enriched with meaningful business features. The next step is to perform SQL analysis to extract valuable business insights.

Using SQL, we will explore customer behavior, sales performance, delivery efficiency, payment trends, and product performance. The queries developed in this notebook simulate real business reporting tasks performed by data analysts.

The SQL concepts covered include filtering, sorting, aggregation, grouping, joins, subqueries, common table expressions (CTEs), and window functions.

In [3]:
# ==========================================================
# Import Required Libraries
# ==========================================================

import pandas as pd
import sqlite3

pd.set_option("display.max_columns", None)

## Load the Engineered Dataset

Load the feature-engineered dataset that was created in the previous notebook.

In [5]:
df = pd.read_csv("../data/processed/engineered_data.csv")

print("Dataset Loaded Successfully!")

df.head()

Dataset Loaded Successfully!

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,purchase_year,purchase_month,purchase_day,purchase_day_name,purchase_hour,purchase_quarter,is_weekend,delivery_days,approval_days,estimated_delivery_gap,late_delivery,total_order_value,high_value_order,revenue_bucket,order_value,customer_order_count,repeat_customer,customer_total_spending,average_order_value_per_customer,installment_category
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,2017,10,2,Monday,10,4,False,8.0,0.0,7.0,False,38.71,False,Medium,116.13,2,True,392.50,196.25,Single Payment
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,2017,10,2,Monday,10,4,False,8.0,0.0,7.0,False,38.71,False,Medium,116.13,2,True,392.50,196.25,Single Payment
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,2017,10,2,Monday,10,4,False,8.0,0.0,7.0,False,38.71,False,Medium,116.13,2,True,392.50,196.25,Single Payment
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08,2018-08-08 18:37:50,2018,7,24,Tuesday,20,3,False,13.0,1.0,5.0,False,141.46,False,Medium,141.46,1,False,141.46,141.46,Single Payment
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,No Title,No Comment,2018-08-18,2018-08-22 19:07:58,2018,8,8,Wednesday,8,3,False,9.0,0.0,17.0,False,179.12,False,High,179.12,1,False,179.12,179.12,Short Installment

## Create SQLite Database

SQLite is a lightweight relational database. We will load our dataset into SQLite so that we can execute SQL queries directly within Jupyter Notebook.

In [7]:
# Create SQLite Connection

conn = sqlite3.connect("ecommerce.db")

print("Database Created Successfully!")

Database Created Successfully!

In [8]:
# Export DataFrame to SQLite

df.to_sql(
    "ecommerce",
    conn,
    if_exists="replace",
    index=False
)

print("Table Created Successfully!")

Table Created Successfully!

In [9]:
query = """
SELECT *
FROM ecommerce
LIMIT 5;
"""

pd.read_sql(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,purchase_year,purchase_month,purchase_day,purchase_day_name,purchase_hour,purchase_quarter,is_weekend,delivery_days,approval_days,estimated_delivery_gap,late_delivery,total_order_value,high_value_order,revenue_bucket,order_value,customer_order_count,repeat_customer,customer_total_spending,average_order_value_per_customer,installment_category
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,2017,10,2,Monday,10,4,0,8.0,0.0,7.0,0,38.71,0,Medium,116.13,2,1,392.50,196.25,Single Payment
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,2017,10,2,Monday,10,4,0,8.0,0.0,7.0,0,38.71,0,Medium,116.13,2,1,392.50,196.25,Single Payment
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,2017,10,2,Monday,10,4,0,8.0,0.0,7.0,0,38.71,0,Medium,116.13,2,1,392.50,196.25,Single Payment
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08,2018-08-08 18:37:50,2018,7,24,Tuesday,20,3,0,13.0,1.0,5.0,0,141.46,0,Medium,141.46,1,0,141.46,141.46,Single Payment
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,No Title,No Comment,2018-08-18,2018-08-22 19:07:58,2018,8,8,Wednesday,8,3,0,9.0,0.0,17.0,0,179.12,0,High,179.12,1,0,179.12,179.12,Short Installment

# 1. Basic SQL Queries

Basic SQL queries are used to retrieve data from a database. In this section, we will learn how to view records, select specific columns, retrieve unique values, and count records.

In [12]:
query = """
SELECT *
FROM ecommerce
LIMIT 5;
"""

pd.read_sql(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,purchase_year,purchase_month,purchase_day,purchase_day_name,purchase_hour,purchase_quarter,is_weekend,delivery_days,approval_days,estimated_delivery_gap,late_delivery,total_order_value,high_value_order,revenue_bucket,order_value,customer_order_count,repeat_customer,customer_total_spending,average_order_value_per_customer,installment_category
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,2017,10,2,Monday,10,4,0,8.0,0.0,7.0,0,38.71,0,Medium,116.13,2,1,392.50,196.25,Single Payment
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,2017,10,2,Monday,10,4,0,8.0,0.0,7.0,0,38.71,0,Medium,116.13,2,1,392.50,196.25,Single Payment
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,2017,10,2,Monday,10,4,0,8.0,0.0,7.0,0,38.71,0,Medium,116.13,2,1,392.50,196.25,Single Payment
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08,2018-08-08 18:37:50,2018,7,24,Tuesday,20,3,0,13.0,1.0,5.0,0,141.46,0,Medium,141.46,1,0,141.46,141.46,Single Payment
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,No Title,No Comment,2018-08-18,2018-08-22 19:07:58,2018,8,8,Wednesday,8,3,0,9.0,0.0,17.0,0,179.12,0,High,179.12,1,0,179.12,179.12,Short Installment

In [13]:
query = """
SELECT
    customer_city,
    customer_state,
    payment_type,
    order_value
FROM ecommerce
LIMIT 10;
"""

pd.read_sql(query, conn)

             customer_city customer_state payment_type  order_value
0                sao paulo             SP  credit_card       116.13
1                sao paulo             SP      voucher       116.13
2                sao paulo             SP      voucher       116.13
3                barreiras             BA       boleto       141.46
4               vianopolis             GO  credit_card       179.12
5  sao goncalo do amarante             RN  credit_card        72.20
6              santo andre             SP  credit_card        28.62
7             congonhinhas             PR  credit_card       175.26
8               santa rosa             RS  credit_card        65.95
9                nilopolis             RJ  credit_card        75.16

In [14]:
query = """
SELECT DISTINCT payment_type
FROM ecommerce;
"""

pd.read_sql(query, conn)

  payment_type
0  credit_card
1      voucher
2       boleto
3   debit_card
4  not_defined
5         None

In [15]:
query = """
SELECT COUNT(*) AS total_records
FROM ecommerce;
"""

pd.read_sql(query, conn)

   total_records
0         119143

In [16]:
query = """
SELECT COUNT(DISTINCT customer_unique_id) AS unique_customers
FROM ecommerce;
"""

pd.read_sql(query, conn)

   unique_customers
0             96096

In [17]:
query = """
SELECT COUNT(DISTINCT order_id) AS total_orders
FROM ecommerce;
"""

pd.read_sql(query, conn)

   total_orders
0         99441

# 2. WHERE Clause

The `WHERE` clause is used to filter records based on specific conditions. It allows analysts to retrieve only the data relevant to a business question instead of scanning the entire dataset.

Common operators:
- = (Equal)
- != or <> (Not Equal)
- > (Greater Than)
- < (Less Than)
- >= (Greater Than or Equal To)
- <= (Less Than or Equal To)
- AND
- OR
- IN
- BETWEEN
- LIKE

In [19]:
query = """
SELECT *
FROM ecommerce
WHERE order_status = 'delivered';
"""

pd.read_sql(query, conn).head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,purchase_year,purchase_month,purchase_day,purchase_day_name,purchase_hour,purchase_quarter,is_weekend,delivery_days,approval_days,estimated_delivery_gap,late_delivery,total_order_value,high_value_order,revenue_bucket,order_value,customer_order_count,repeat_customer,customer_total_spending,average_order_value_per_customer,installment_category
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,2017,10,2,Monday,10,4,0,8.0,0.0,7.0,0,38.71,0,Medium,116.13,2,1,392.50,196.25,Single Payment
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,2017,10,2,Monday,10,4,0,8.0,0.0,7.0,0,38.71,0,Medium,116.13,2,1,392.50,196.25,Single Payment
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,2017,10,2,Monday,10,4,0,8.0,0.0,7.0,0,38.71,0,Medium,116.13,2,1,392.50,196.25,Single Payment
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08,2018-08-08 18:37:50,2018,7,24,Tuesday,20,3,0,13.0,1.0,5.0,0,141.46,0,Medium,141.46,1,0,141.46,141.46,Single Payment
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,No Title,No Comment,2018-08-18,2018-08-22 19:07:58,2018,8,8,Wednesday,8,3,0,9.0,0.0,17.0,0,179.12,0,High,179.12,1,0,179.12,179.12,Short Installment

In [20]:
query = """
SELECT
    customer_city,
    customer_state,
    order_value
FROM ecommerce
WHERE customer_state = 'SP';
"""

pd.read_sql(query, conn)

             customer_city customer_state  order_value
0                sao paulo             SP       116.13
1                sao paulo             SP       116.13
2                sao paulo             SP       116.13
3              santo andre             SP        28.62
4                 sorocaba             SP       339.52
...                    ...            ...          ...
50260              jundiai             SP       165.96
50261            sao paulo             SP        37.94
50262            sao paulo             SP       155.99
50263  sao jose dos campos             SP        85.08
50264         praia grande             SP       195.00

[50265 rows x 3 columns]

In [21]:
query = """
SELECT
    order_id,
    order_value,
    customer_state
FROM ecommerce
WHERE order_value > 500;
"""

pd.read_sql(query, conn)

                              order_id  order_value customer_state
0     403b97836b0c04a622354cf531062e5f      1376.45             RJ
1     434d158e96bdd6972ad6e6d73ddcfd22       508.17             PE
2     f271576bed568e896f99eb710cd3a6f8       824.76             BA
3     f271576bed568e896f99eb710cd3a6f8       824.76             BA
4     6b860b35691d486e45dc98e3514ec5f6       574.36             SP
...                                ...          ...            ...
8638  2ff4dba9b7e65ee15034ed2b0004048d      1013.59             MG
8639  e8fd20068b9f7e6ec07068bb7537f781       748.24             SP
8640  e8fd20068b9f7e6ec07068bb7537f781       748.24             SP
8641  aa04ef5214580b06b10e2a378300db44       778.86             MG
8642  aa04ef5214580b06b10e2a378300db44       778.86             MG

[8643 rows x 3 columns]

In [22]:
query = """
SELECT
    order_id,
    payment_type,
    order_value
FROM ecommerce
WHERE payment_type = 'credit_card';
"""

pd.read_sql(query, conn)

                               order_id payment_type  order_value
0      e481f51cbdc54678b7cc49136f2d6af7  credit_card       116.13
1      47770eb9100c2d0c44946d9cf07ec65d  credit_card       179.12
2      949d5b44dbf5de918fe9c16f97b45f8a  credit_card        72.20
3      ad21c59c0840e6cb83a9ceb5573f8159  credit_card        28.62
4      a4591c265e18cb1dcee52889e2d8acc3  credit_card       175.26
...                                 ...          ...          ...
87771  9c5dedf39a927c1b2549525ed64a053c  credit_card        85.08
87772  63943bddc261676b46f01ca7ac2f7bd8  credit_card       195.00
87773  83c1379a015df1e13d02aae0204711ab  credit_card       271.01
87774  11c177c8e97725db2631073c19f07b62  credit_card       441.16
87775  11c177c8e97725db2631073c19f07b62  credit_card       441.16

[87776 rows x 3 columns]

In [23]:
query = """
SELECT
    order_id,
    customer_state,
    order_status
FROM ecommerce
WHERE customer_state = 'SP'
AND order_status = 'delivered';
"""

pd.read_sql(query, conn)

                               order_id customer_state order_status
0      e481f51cbdc54678b7cc49136f2d6af7             SP    delivered
1      e481f51cbdc54678b7cc49136f2d6af7             SP    delivered
2      e481f51cbdc54678b7cc49136f2d6af7             SP    delivered
3      ad21c59c0840e6cb83a9ceb5573f8159             SP    delivered
4      e69bfb5eb88e0ed6a785585b27e16dbf             SP    delivered
...                                 ...            ...          ...
48811  c22a47117b6a87c967b0c278488110c1             SP    delivered
48812  0e4b26f1fb99fc0f0472dd5f403d36d4             SP    delivered
48813  880675dff2150932f1601e1c07eadeeb             SP    delivered
48814  9c5dedf39a927c1b2549525ed64a053c             SP    delivered
48815  63943bddc261676b46f01ca7ac2f7bd8             SP    delivered

[48816 rows x 3 columns]

In [24]:
query = """
SELECT
    customer_state,
    customer_city
FROM ecommerce
WHERE customer_state = 'SP'
OR customer_state = 'RJ';
"""

pd.read_sql(query, conn)

      customer_state        customer_city
0                 SP            sao paulo
1                 SP            sao paulo
2                 SP            sao paulo
3                 SP          santo andre
4                 RJ            nilopolis
...              ...                  ...
65778             SP            sao paulo
65779             SP  sao jose dos campos
65780             SP         praia grande
65781             RJ              japuiba
65782             RJ              japuiba

[65783 rows x 2 columns]

In [25]:
query = """
SELECT
    order_id,
    order_value
FROM ecommerce
WHERE order_value BETWEEN 200 AND 1000;
"""

pd.read_sql(query, conn)

                               order_id  order_value
0      e69bfb5eb88e0ed6a785585b27e16dbf       339.52
1      e69bfb5eb88e0ed6a785585b27e16dbf       339.52
2      e6ce16cb79ec1d90b1da9085a6118aeb       259.06
3      e6ce16cb79ec1d90b1da9085a6118aeb       259.06
4      83018ec114eee8641c97e08f7b4e926f       278.91
...                                 ...          ...
29357  aa04ef5214580b06b10e2a378300db44       778.86
29358  aa04ef5214580b06b10e2a378300db44       778.86
29359  83c1379a015df1e13d02aae0204711ab       271.01
29360  11c177c8e97725db2631073c19f07b62       441.16
29361  11c177c8e97725db2631073c19f07b62       441.16

[29362 rows x 2 columns]

In [26]:
query = """
SELECT
    customer_state,
    order_id
FROM ecommerce
WHERE customer_state IN ('SP','RJ','MG');
"""

pd.read_sql(query, conn)

      customer_state                          order_id
0                 SP  e481f51cbdc54678b7cc49136f2d6af7
1                 SP  e481f51cbdc54678b7cc49136f2d6af7
2                 SP  e481f51cbdc54678b7cc49136f2d6af7
3                 SP  ad21c59c0840e6cb83a9ceb5573f8159
4                 RJ  6514b8ad8028c9f2cc2374ded245783f
...              ...                               ...
79597             SP  880675dff2150932f1601e1c07eadeeb
79598             SP  9c5dedf39a927c1b2549525ed64a053c
79599             SP  63943bddc261676b46f01ca7ac2f7bd8
79600             RJ  11c177c8e97725db2631073c19f07b62
79601             RJ  11c177c8e97725db2631073c19f07b62

[79602 rows x 2 columns]

In [27]:
query = """
SELECT DISTINCT customer_city
FROM ecommerce
WHERE customer_city LIKE 'S%';
"""

pd.read_sql(query, conn)

                 customer_city
0                    sao paulo
1      sao goncalo do amarante
2                  santo andre
3                   santa rosa
4                     sorocaba
..                         ...
546                   sambaiba
547                sandolandia
548     santo antonio de goias
549  sao benedito do rio preto
550         sao jose do serido

[551 rows x 1 columns]

In [28]:
query = """
SELECT
    order_id,
    order_status
FROM ecommerce
WHERE order_status != 'delivered';
"""

pd.read_sql(query, conn)

                              order_id order_status
0     136cce7faa42fdb2cefd53fdc79a6098     invoiced
1     ee64d42b8cf066f35eac1cf57de1aa85      shipped
2     0760a852e4e9d89eb77bf631eaaf1c84     invoiced
3     15bed8e2fec7fdbadb186b57c46c92f2   processing
4     6942b8da583c2f9957e990d028607019      shipped
...                                ...          ...
3415  3a3cddda5a7c27851bd96c3313412840     canceled
3416  e9e64a17afa9653aacf2616d94c005b8   processing
3417  a89abace0dcc01eeb267a9660b5ac126     canceled
3418  a69ba794cc7deb415c3e15a0a3877e69  unavailable
3419  5fabc81b6322c8443648e1b21a6fef21  unavailable

[3420 rows x 2 columns]

# 3. ORDER BY Clause

The `ORDER BY` clause is used to sort the query results in ascending (`ASC`) or descending (`DESC`) order. Sorting helps analysts identify top-performing products, highest revenue orders, and lowest-performing categories.

By default, SQL sorts data in ascending order.

In [30]:
query = """
SELECT
    order_id,
    order_value
FROM ecommerce
ORDER BY order_value ASC;
"""

pd.read_sql(query, conn).head(10)

                           order_id  order_value
0  8e24261a7e58791d10cb1bf9da94df5c          0.0
1  c272bcd21c287498b4883c7512019702          0.0
2  37553832a3a89c9b2db59701c357ca67          0.0
3  d57e15fb07fd180f06ab3926b39edcd2          0.0
4  00b1cb0320190ca0daa2c88b35206009          0.0
5  2f634e2cebf8c0283e7ef0989f77d217          0.0
6  ee0db22a8e742b752914016708470ec8          0.0
7  ed3efbd3a87bea76c2812c66a0b32219          0.0
8  6ad57aecbae806a7e9cc2cdb6b380711          0.0
9  df8282afe61008dc26c6c31011474d02          0.0

In [31]:
query = """
SELECT
    order_id,
    order_value
FROM ecommerce
ORDER BY order_value DESC;
"""

pd.read_sql(query, conn).head(10)

                           order_id  order_value
0  03caa2c082116e1d31e67e9ae3700499     13664.08
1  03caa2c082116e1d31e67e9ae3700499     13664.08
2  03caa2c082116e1d31e67e9ae3700499     13664.08
3  03caa2c082116e1d31e67e9ae3700499     13664.08
4  03caa2c082116e1d31e67e9ae3700499     13664.08
5  03caa2c082116e1d31e67e9ae3700499     13664.08
6  03caa2c082116e1d31e67e9ae3700499     13664.08
7  03caa2c082116e1d31e67e9ae3700499     13664.08
8  fa65dad1b0e818e3ccc5cb0e39231352     13281.71
9  fa65dad1b0e818e3ccc5cb0e39231352     13281.71

In [32]:
query = """
SELECT
    customer_unique_id,
    customer_total_spending
FROM ecommerce
ORDER BY customer_total_spending DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                 customer_unique_id  customer_total_spending
0  8af7ac63b2efbcbd88e5b11505e8098a                385169.59
1  8af7ac63b2efbcbd88e5b11505e8098a                385169.59
2  8af7ac63b2efbcbd88e5b11505e8098a                385169.59
3  8af7ac63b2efbcbd88e5b11505e8098a                385169.59
4  8af7ac63b2efbcbd88e5b11505e8098a                385169.59
5  8af7ac63b2efbcbd88e5b11505e8098a                385169.59
6  8af7ac63b2efbcbd88e5b11505e8098a                385169.59
7  8af7ac63b2efbcbd88e5b11505e8098a                385169.59
8  8af7ac63b2efbcbd88e5b11505e8098a                385169.59
9  8af7ac63b2efbcbd88e5b11505e8098a                385169.59

In [33]:
query = """
SELECT
    order_id,
    delivery_days
FROM ecommerce
ORDER BY delivery_days DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                           order_id  delivery_days
0  ca07593549f1816d26a572e06dc1eab6          209.0
1  1b3190b2dfa9d789e1f14c05b647a14a          208.0
2  440d0d17af552815d15a9e41abe49359          195.0
3  0f4519c5f1c541ddec9f21b3bddd533a          194.0
4  2fb597c2f772eca01b1f5c561bf6cc7b          194.0
5  285ab9426d6982034523a855f55a885e          194.0
6  47b40429ed8cce3aee9199792275433f          191.0
7  2fe324febf907e3ea3f2aa9650869fa5          189.0
8  2d7561026d542c8dbd8f0daeadf67a43          188.0
9  437222e3fd1b07396f1d9ba8c15fba59          187.0

In [34]:
query = """
SELECT DISTINCT
    customer_city
FROM ecommerce
ORDER BY customer_city ASC;
"""

pd.read_sql(query, conn)

            customer_city
0     abadia dos dourados
1               abadiania
2                  abaete
3              abaetetuba
4                 abaiara
...                   ...
4114             xinguara
4115          xique-xique
4116             zacarias
4117              ze doca
4118               zortea

[4119 rows x 1 columns]

In [35]:
query = """
SELECT
    customer_state,
    order_id,
    order_value
FROM ecommerce
ORDER BY
    customer_state ASC,
    order_value DESC;
"""

pd.read_sql(query, conn)

       customer_state                          order_id  order_value
0                  AC  37fef9185066b091254533c2192edd72      1990.36
1                  AC  37fef9185066b091254533c2192edd72      1990.36
2                  AC  2bcf1f79964f8b4f4f62f19441601b1a      1251.70
3                  AC  185e7ea81e4cf0fc1d2f4e8e38e8e7e3       905.93
4                  AC  ad7d812f43f6308a7105fecab91fe3c1       861.26
...               ...                               ...          ...
119138             TO  b50788fa41255b57ddf0782d1fc0ad2b        35.53
119139             TO  9d9f7fce2886a9587f0a42a1366a1392        33.77
119140             TO  d72e8cc4d5efd1b5149f68dffc423772        31.77
119141             TO  af8822dc30a41edce5b644f195e3f269        28.77
119142             TO  90e258ad907d8401c4f1107ea9e55f1b         0.00

[119143 rows x 3 columns]

# 4. Aggregate Functions

Aggregate functions perform calculations on a group of rows and return a single summarized value. They are widely used in business reporting to calculate KPIs such as total revenue, average order value, highest sales, and customer counts.

The aggregate functions covered in this section are:
- COUNT()
- SUM()
- AVG()
- MIN()
- MAX()

In [37]:
query = """
SELECT COUNT(DISTINCT order_id) AS total_orders
FROM ecommerce;
"""

pd.read_sql(query, conn)

   total_orders
0         99441

In [38]:
query = """
SELECT ROUND(SUM(order_value), 2) AS total_revenue
FROM ecommerce;
"""

pd.read_sql(query, conn)

   total_revenue
0    25737892.55

In [39]:
query = """
SELECT ROUND(AVG(order_value), 2) AS average_order_value
FROM ecommerce;
"""

pd.read_sql(query, conn)

   average_order_value
0               216.03

In [40]:
query = """
SELECT MAX(order_value) AS highest_order_value
FROM ecommerce;
"""

pd.read_sql(query, conn)

   highest_order_value
0             13664.08

In [41]:
query = """
SELECT MIN(order_value) AS lowest_order_value
FROM ecommerce;
"""

pd.read_sql(query, conn)

   lowest_order_value
0                 0.0

In [42]:
query = """
SELECT ROUND(AVG(delivery_days), 2) AS average_delivery_days
FROM ecommerce;
"""

pd.read_sql(query, conn)

   average_delivery_days
0                  12.02

In [43]:
query = """
SELECT MAX(delivery_days) AS longest_delivery_days
FROM ecommerce;
"""

pd.read_sql(query, conn)

   longest_delivery_days
0                  209.0

In [44]:
query = """
SELECT ROUND(AVG(delivery_days), 2) AS average_delivery_days
FROM ecommerce;
"""

pd.read_sql(query, conn)

   average_delivery_days
0                  12.02

In [45]:
query = """
SELECT MAX(delivery_days) AS longest_delivery_days
FROM ecommerce;
"""

pd.read_sql(query, conn)

   longest_delivery_days
0                  209.0

In [46]:
query = """
SELECT ROUND(AVG(customer_total_spending), 2) AS average_customer_spending
FROM ecommerce;
"""

pd.read_sql(query, conn)

   average_customer_spending
0                    1031.47

# 5. GROUP BY Clause

The `GROUP BY` clause groups rows that have the same values into summary rows. It is commonly used with aggregate functions such as COUNT(), SUM(), AVG(), MIN(), and MAX() to generate business reports and key performance indicators (KPIs).

In this section, we will analyze sales, customers, delivery performance, and payment methods by grouping different attributes.

In [48]:
query = """
SELECT
    customer_state,
    COUNT(DISTINCT order_id) AS total_orders
FROM ecommerce
GROUP BY customer_state
ORDER BY total_orders DESC;
"""

pd.read_sql(query, conn)

   customer_state  total_orders
0              SP         41746
1              RJ         12852
2              MG         11635
3              RS          5466
4              PR          5045
5              SC          3637
6              BA          3380
7              DF          2140
8              ES          2033
9              GO          2020
10             PE          1652
11             CE          1336
12             PA           975
13             MT           907
14             MA           747
15             MS           715
16             PB           536
17             PI           495
18             RN           485
19             AL           413
20             SE           350
21             TO           280
22             RO           253
23             AM           148
24             AC            81
25             AP            68
26             RR            46

In [49]:
query = """
SELECT
    customer_state,
    ROUND(SUM(price + freight_value),2) AS total_revenue
FROM ecommerce
GROUP BY customer_state
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conn)

   customer_state  total_revenue
0              SP     6234533.82
1              RJ     2247128.32
2              MG     1928571.09
3              RS      934286.75
4              PR      832059.40
5              BA      650220.38
6              SC      632514.14
7              GO      368997.61
8              DF      367750.15
9              ES      336438.54
10             PE      334467.37
11             CE      290599.59
12             PA      224924.18
13             MT      203768.97
14             MA      155510.26
15             PB      151482.79
16             MS      141346.92
17             RN      114747.31
18             PI      114729.56
19             AL       99781.70
20             SE       75495.89
21             TO       69702.51
22             RO       58681.50
23             AM       28549.04
24             AC       20861.50
25             AP       16517.39
26             RR       10064.62

In [50]:
query = """
SELECT
    customer_state,
    ROUND(AVG(delivery_days),2) AS average_delivery_days
FROM ecommerce
GROUP BY customer_state
ORDER BY average_delivery_days;
"""

pd.read_sql(query, conn)

   customer_state  average_delivery_days
0              SP                   8.27
1              MG                  11.50
2              PR                  11.52
3              DF                  12.50
4              SC                  14.51
5              RS                  14.70
6              RJ                  14.77
7              GO                  14.90
8              MS                  15.06
9              ES                  15.24
10             TO                  16.66
11             MT                  17.52
12             PE                  17.77
13             BA                  18.73
14             PI                  18.89
15             RN                  19.18
16             RO                  19.23
17             PB                  20.11
18             AC                  20.17
19             CE                  20.34
20             SE                  20.89
21             MA                  21.19
22             PA                  23.27
23             AL                  24.13
24             AM                  26.06
25             AP                  27.66
26             RR                  27.83

In [51]:
query = """
SELECT
    payment_type,
    COUNT(DISTINCT order_id) AS total_orders
FROM ecommerce
GROUP BY payment_type
ORDER BY total_orders DESC;
"""

pd.read_sql(query, conn)

  payment_type  total_orders
0  credit_card         76505
1       boleto         19784
2      voucher          3866
3   debit_card          1528
4  not_defined             3
5         None             1

In [52]:
query = """
SELECT
    product_category_name,
    ROUND(SUM(price + freight_value),2) AS total_revenue
FROM ecommerce
GROUP BY product_category_name
ORDER BY total_revenue DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

    product_category_name  total_revenue
0            beleza_saude     1491397.76
1      relogios_presentes     1358845.59
2         cama_mesa_banho     1327662.02
3           esporte_lazer     1205197.85
4  informatica_acessorios     1104362.03
5        moveis_decoracao      955367.22
6   utilidades_domesticas      823623.50
7              cool_stuff      752702.21
8              automotivo      714431.95
9      ferramentas_jardim      625387.31

In [53]:
query = """
SELECT
    product_category_name,
    ROUND(AVG(review_score),2) AS average_review_score
FROM ecommerce
GROUP BY product_category_name
ORDER BY average_review_score DESC;
"""

pd.read_sql(query, conn)

                            product_category_name  average_review_score
0                               cds_dvds_musicais                  4.64
1                   fashion_roupa_infanto_juvenil                  4.50
2                          livros_interesse_geral                  4.44
3                               livros_importados                  4.42
4                                          flores                  4.42
..                                            ...                   ...
70  portateis_cozinha_e_preparadores_de_alimentos                  3.27
71                                fraldas_higiene                  3.26
72                                       pc_gamer                  3.10
73                             seguros_e_servicos                  2.50
74                                           None                  1.74

[75 rows x 2 columns]

In [54]:
query = """
SELECT
    payment_type,
    ROUND(AVG(order_value),2) AS average_order_value
FROM ecommerce
GROUP BY payment_type
ORDER BY average_order_value DESC;
"""

pd.read_sql(query, conn)

  payment_type  average_order_value
0      voucher               667.66
1  credit_card               194.03
2       boleto               178.22
3   debit_card               150.56
4         None               143.46
5  not_defined                 0.00

In [55]:
query = """
SELECT
    payment_type,
    ROUND(AVG(order_value),2) AS average_order_value
FROM ecommerce
GROUP BY payment_type
ORDER BY average_order_value DESC;
"""

pd.read_sql(query, conn)

  payment_type  average_order_value
0      voucher               667.66
1  credit_card               194.03
2       boleto               178.22
3   debit_card               150.56
4         None               143.46
5  not_defined                 0.00

In [56]:
query = """
SELECT
    customer_state,
    COUNT(DISTINCT customer_unique_id) AS total_customers
FROM ecommerce
GROUP BY customer_state
ORDER BY total_customers DESC;
"""

pd.read_sql(query, conn)

   customer_state  total_customers
0              SP            40302
1              RJ            12384
2              MG            11259
3              RS             5277
4              PR             4882
5              SC             3534
6              BA             3277
7              DF             2075
8              ES             1964
9              GO             1952
10             PE             1609
11             CE             1313
12             PA              949
13             MT              876
14             MA              726
15             MS              694
16             PB              519
17             PI              482
18             RN              474
19             AL              401
20             SE              342
21             TO              273
22             RO              240
23             AM              143
24             AC               77
25             AP               67
26             RR               45

# 6. HAVING Clause

The `HAVING` clause is used to filter grouped data after applying the `GROUP BY` clause. While the `WHERE` clause filters individual rows before grouping, the `HAVING` clause filters the summarized groups based on aggregate conditions.

It is commonly used in business reporting to identify high-performing states, top-selling product categories, and frequently used payment methods.

In [58]:
query = """
SELECT
    customer_state,
    COUNT(DISTINCT order_id) AS total_orders
FROM ecommerce
GROUP BY customer_state
HAVING COUNT(DISTINCT order_id) > 1000
ORDER BY total_orders DESC;
"""

pd.read_sql(query, conn)

   customer_state  total_orders
0              SP         41746
1              RJ         12852
2              MG         11635
3              RS          5466
4              PR          5045
5              SC          3637
6              BA          3380
7              DF          2140
8              ES          2033
9              GO          2020
10             PE          1652
11             CE          1336

In [59]:
query = """
SELECT
    product_category_name,
    ROUND(SUM(price + freight_value),2) AS total_revenue
FROM ecommerce
GROUP BY product_category_name
HAVING SUM(price + freight_value) > 100000
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conn)

                product_category_name  total_revenue
0                        beleza_saude     1491397.76
1                  relogios_presentes     1358845.59
2                     cama_mesa_banho     1327662.02
3                       esporte_lazer     1205197.85
4              informatica_acessorios     1104362.03
5                    moveis_decoracao      955367.22
6               utilidades_domesticas      823623.50
7                          cool_stuff      752702.21
8                          automotivo      714431.95
9                  ferramentas_jardim      625387.31
10                         brinquedos      582218.11
11                              bebes      506539.48
12                         perfumaria      471766.76
13                          telefonia      413871.98
14                  moveis_escritorio      359171.62
15                          papelaria      288342.44
16                           pet_shop      264442.62
17                                pcs      253374.41
18              instrumentos_musicais      230579.09
19                            Unknown      222703.08
20                    eletroportateis      218726.30
21                        eletronicos      214862.55
22        fashion_bolsas_e_acessorios      197052.25
23                     consoles_games      187551.16
24                   malas_acessorios      180577.27
25  construcao_ferramentas_construcao      169812.63
26                 eletrodomesticos_2      135945.04
27                    casa_construcao      102212.32
28                   eletrodomesticos      101179.43

In [60]:
query = """
SELECT
    payment_type,
    ROUND(AVG(order_value),2) AS average_order_value
FROM ecommerce
GROUP BY payment_type
HAVING AVG(order_value) > 500
ORDER BY average_order_value DESC;
"""

pd.read_sql(query, conn)

  payment_type  average_order_value
0      voucher               667.66

In [61]:
query = """
SELECT
    product_category_name,
    ROUND(AVG(review_score),2) AS average_review_score
FROM ecommerce
GROUP BY product_category_name
HAVING AVG(review_score) > 4.5
ORDER BY average_review_score DESC;
"""

pd.read_sql(query, conn)

  product_category_name  average_review_score
0     cds_dvds_musicais                  4.64

In [62]:
query = """
SELECT
    customer_state,
    ROUND(AVG(delivery_days),2) AS average_delivery_days
FROM ecommerce
GROUP BY customer_state
HAVING AVG(delivery_days) < 10
ORDER BY average_delivery_days;
"""

pd.read_sql(query, conn)

  customer_state  average_delivery_days
0             SP                   8.27

In [63]:
query = """
SELECT
    seller_id,
    COUNT(product_id) AS products_sold
FROM ecommerce
GROUP BY seller_id
HAVING COUNT(product_id) > 100
ORDER BY products_sold DESC;
"""

pd.read_sql(query, conn)

                            seller_id  products_sold
0    4a3ca9315b744ce9f8e9374361493884           2155
1    6560211a19b47992c3666cc44a7e94c0           2130
2    1f50f920176fa81dab994f9023523100           2017
3    cc419e0650a3c5ba77189a1882b7556a           1893
4    da8622b14eb17ae2831f4ac5b9dab84a           1662
..                                ...            ...
244  3be634553519fb6536a03e1358e9fdc7            103
245  9674754b5a0cb32b638cec001178f799            102
246  5c243662ce92d84573bfaff24c3e3700            102
247  0509040ea3fe50071181bbc359eb7738            102
248  f84a00e60c73a49e7e851c9bdca3a5bb            101

[249 rows x 2 columns]

# 7. CASE WHEN

The `CASE WHEN` statement is used to apply conditional logic in SQL. It evaluates one or more conditions and returns a value based on the first matching condition.

It is commonly used to:
- Categorize customers
- Classify orders
- Create business labels
- Generate custom reporting fields

In [65]:
query = """
SELECT
    order_id,
    order_value,
    CASE
        WHEN order_value < 100 THEN 'Low Value'
        WHEN order_value BETWEEN 100 AND 500 THEN 'Medium Value'
        ELSE 'High Value'
    END AS order_category
FROM ecommerce
LIMIT 10;
"""

pd.read_sql(query, conn)

                           order_id  order_value order_category
0  e481f51cbdc54678b7cc49136f2d6af7       116.13   Medium Value
1  e481f51cbdc54678b7cc49136f2d6af7       116.13   Medium Value
2  e481f51cbdc54678b7cc49136f2d6af7       116.13   Medium Value
3  53cdb2fc8bc7dce0b6741e2150273451       141.46   Medium Value
4  47770eb9100c2d0c44946d9cf07ec65d       179.12   Medium Value
5  949d5b44dbf5de918fe9c16f97b45f8a        72.20      Low Value
6  ad21c59c0840e6cb83a9ceb5573f8159        28.62      Low Value
7  a4591c265e18cb1dcee52889e2d8acc3       175.26   Medium Value
8  136cce7faa42fdb2cefd53fdc79a6098        65.95      Low Value
9  6514b8ad8028c9f2cc2374ded245783f        75.16      Low Value

In [66]:
query = """
SELECT
    order_id,
    delivery_days,
    late_delivery,
    CASE
        WHEN late_delivery = 1 THEN 'Late Delivery'
        ELSE 'On Time'
    END AS delivery_status
FROM ecommerce
LIMIT 10;
"""

pd.read_sql(query, conn)

,order_id,delivery_days,late_delivery,delivery_status
0,e481f51cbdc54678b7cc49136f2d6af7,8.0,0,On Time
1,e481f51cbdc54678b7cc49136f2d6af7,8.0,0,On Time
2,e481f51cbdc54678b7cc49136f2d6af7,8.0,0,On Time
3,53cdb2fc8bc7dce0b6741e2150273451,13.0,0,On Time
4,47770eb9100c2d0c44946d9cf07ec65d,9.0,0,On Time
5,949d5b44dbf5de918fe9c16f97b45f8a,13.0,0,On Time
6,ad21c59c0840e6cb83a9ceb5573f8159,2.0,0,On Time
7,a4591c265e18cb1dcee52889e2d8acc3,16.0,0,On Time
8,136cce7faa42fdb2cefd53fdc79a6098,NaN,0,On Time
9,6514b8ad8028c9f2cc2374ded245783f,9.0,0,On Time

In [67]:
query = """
SELECT
    customer_unique_id,
    customer_order_count,
    CASE
        WHEN customer_order_count = 1 THEN 'New Customer'
        ELSE 'Repeat Customer'
    END AS customer_type
FROM ecommerce
LIMIT 10;
"""

pd.read_sql(query, conn)

                 customer_unique_id  customer_order_count    customer_type
0  7c396fd4830fd04220f754e42b4e5bff                     2  Repeat Customer
1  7c396fd4830fd04220f754e42b4e5bff                     2  Repeat Customer
2  7c396fd4830fd04220f754e42b4e5bff                     2  Repeat Customer
3  af07308b275d755c9edb36a90c618231                     1     New Customer
4  3a653a41f6f9fc3d2a113cf8398680e8                     1     New Customer
5  7c142cf63193a1473d2e66489a9ae977                     1     New Customer
6  72632f0f9dd73dfee390c9b22eb56dd6                     1     New Customer
7  80bb27c7c16e8f973207a5086ab329e2                     1     New Customer
8  36edbb3fb164b1f16485364b6fb04c73                     1     New Customer
9  932afa1e708222e5821dac9cd5db4cae                     1     New Customer

In [68]:
query = """
SELECT
    payment_installments,
    CASE
        WHEN payment_installments = 1 THEN 'Single Payment'
        WHEN payment_installments BETWEEN 2 AND 3 THEN 'Short Installment'
        WHEN payment_installments BETWEEN 4 AND 6 THEN 'Medium Installment'
        ELSE 'Long Installment'
    END AS installment_category
FROM ecommerce
LIMIT 10;
"""

pd.read_sql(query, conn)

   payment_installments installment_category
0                   1.0       Single Payment
1                   1.0       Single Payment
2                   1.0       Single Payment
3                   1.0       Single Payment
4                   3.0    Short Installment
5                   1.0       Single Payment
6                   1.0       Single Payment
7                   6.0   Medium Installment
8                   1.0       Single Payment
9                   3.0    Short Installment

In [69]:
query = """
SELECT
    review_score,
    CASE
        WHEN review_score >= 4 THEN 'Positive'
        WHEN review_score = 3 THEN 'Neutral'
        ELSE 'Negative'
    END AS review_sentiment
FROM ecommerce
LIMIT 10;
"""

pd.read_sql(query, conn)

   review_score review_sentiment
0           4.0         Positive
1           4.0         Positive
2           4.0         Positive
3           4.0         Positive
4           5.0         Positive
5           5.0         Positive
6           5.0         Positive
7           4.0         Positive
8           2.0         Negative
9           5.0         Positive

In [70]:
query = """
SELECT
    product_category_name,
    price,
    CASE
        WHEN price < 50 THEN 'Budget'
        WHEN price BETWEEN 50 AND 200 THEN 'Standard'
        ELSE 'Premium'
    END AS product_segment
FROM ecommerce
LIMIT 10;
"""

pd.read_sql(query, conn)

   product_category_name   price product_segment
0  utilidades_domesticas   29.99          Budget
1  utilidades_domesticas   29.99          Budget
2  utilidades_domesticas   29.99          Budget
3             perfumaria  118.70        Standard
4             automotivo  159.90        Standard
5               pet_shop   45.00          Budget
6              papelaria   19.90          Budget
7             automotivo  147.90        Standard
8                Unknown   49.90          Budget
9             automotivo   59.99        Standard

# 8. Subqueries

A subquery is a query nested inside another SQL query. It allows us to use the result of one query as the input for another query.

Subqueries are commonly used to compare values against averages, identify top-performing customers, filter records dynamically, and solve complex business problems.

In [72]:
query = """
SELECT
    order_id,
    order_value
FROM ecommerce
WHERE order_value >
(
    SELECT AVG(order_value)
    FROM ecommerce
);
"""

pd.read_sql(query, conn)

                               order_id  order_value
0      e69bfb5eb88e0ed6a785585b27e16dbf       339.52
1      e69bfb5eb88e0ed6a785585b27e16dbf       339.52
2      e6ce16cb79ec1d90b1da9085a6118aeb       259.06
3      e6ce16cb79ec1d90b1da9085a6118aeb       259.06
4      403b97836b0c04a622354cf531062e5f      1376.45
...                                 ...          ...
28990  aa04ef5214580b06b10e2a378300db44       778.86
28991  aa04ef5214580b06b10e2a378300db44       778.86
28992  83c1379a015df1e13d02aae0204711ab       271.01
28993  11c177c8e97725db2631073c19f07b62       441.16
28994  11c177c8e97725db2631073c19f07b62       441.16

[28995 rows x 2 columns]

In [73]:
query = """
SELECT
    product_id,
    product_category_name,
    price
FROM ecommerce
WHERE price >
(
    SELECT AVG(price)
    FROM ecommerce
)
LIMIT 20;
"""

pd.read_sql(query, conn)

,product_id,product_category_name,price
0,aa4383b373c6aca5d8797843e5594415,automotivo,159.90
1,060cb19345d90064d1015407193c233d,automotivo,147.90
2,9a78fb9862b10749a117f7fc3c31f051,moveis_escritorio,149.99
3,9a78fb9862b10749a117f7fc3c31f051,moveis_escritorio,149.99
4,009c09f439988bc06a93d6b8186dce73,perfumaria,132.40
5,638bbb2a5e4f360b71f332ddfebfd672,construcao_ferramentas_construcao,1299.00
6,bb7181410b4e02f93f3697f765db53c7,bebes,129.99
7,ba74c6b75d2ad7503175809688d5a03c,relogios_presentes,178.99
8,cafd558df4c3c9d1c338ba6930ea9a62,bebes,279.00
9,2d8f2be4f08788ee3bf5356af2b2ee6c,climatizacao,186.90
10,c6c1f263e076bd9c1f1640250a5d0c29,perfumaria,179.00
11,c7df652246ed7b3300aaf46960c141e4,beleza_saude,445.00
12,be021417a6acb56b9b50d3fd2714baa8,utilidades_domesticas,339.00
13,e251ebd2858be1aa7d9b2087a6992580,ferramentas_jardim,139.00
14,60184212dae4e6b0da32bf54271a8c4a,relogios_presentes,369.00
15,12087840651e83b48206b82c213b76fd,esporte_lazer,299.00
16,db56f6d2b04c89eae4daba188842fd7b,malas_acessorios,199.00
17,d457916b4fdc60154ed93b5dd3e6fd69,construcao_ferramentas_construcao,329.90
18,d457916b4fdc60154ed93b5dd3e6fd69,construcao_ferramentas_construcao,329.90
19,e932008cf0ea7c93a077dd8d7e5f49eb,climatizacao,190.00

In [74]:
query = """
SELECT DISTINCT
    customer_unique_id,
    customer_total_spending
FROM ecommerce
WHERE customer_total_spending >
(
    SELECT AVG(customer_total_spending)
    FROM ecommerce
)
ORDER BY customer_total_spending DESC;
"""

pd.read_sql(query, conn)

                    customer_unique_id  customer_total_spending
0     8af7ac63b2efbcbd88e5b11505e8098a                385169.59
1     85963fd37bfd387aa6d915d8a1065486                253278.72
2     9a736b248f67d166d2fbb006bcb877c3                223818.84
3     c4b224d2c784bae11ae98b6ae9f2454c                166671.00
4     6fbc7cdadbb522125f4b27ae9dee4060                148544.28
...                                ...                      ...
3045  6d8a1ff2b74ef9d939013151ef4d95cf                  1032.93
3046  5b8a75e77489899ad9e6d57273aafd7f                  1032.32
3047  bc867ebfaaeb874d54cbf1da33fd4a1b                  1031.96
3048  0b8f908a3b8e307be5c917414bc8275d                  1031.69
3049  2ac5e7e1668d672b41e9000fb19bee20                  1031.69

[3050 rows x 2 columns]

In [75]:
query = """
SELECT
    order_id,
    delivery_days
FROM ecommerce
WHERE delivery_days =
(
    SELECT MAX(delivery_days)
    FROM ecommerce
);
"""

pd.read_sql(query, conn)

                           order_id  delivery_days
0  ca07593549f1816d26a572e06dc1eab6          209.0

In [76]:
query = """
SELECT
    customer_state,
    ROUND(SUM(price + freight_value),2) AS total_revenue
FROM ecommerce
GROUP BY customer_state
HAVING SUM(price + freight_value) >
(
    SELECT AVG(state_revenue)
    FROM
    (
        SELECT
            SUM(price + freight_value) AS state_revenue
        FROM ecommerce
        GROUP BY customer_state
    )
)
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conn)

  customer_state  total_revenue
0             SP     6234533.82
1             RJ     2247128.32
2             MG     1928571.09
3             RS      934286.75
4             PR      832059.40
5             BA      650220.38
6             SC      632514.14

In [77]:
query = """
SELECT
    customer_unique_id,
    COUNT(DISTINCT order_id) AS total_orders
FROM ecommerce
GROUP BY customer_unique_id
HAVING COUNT(DISTINCT order_id) >
(
    SELECT AVG(order_count)
    FROM
    (
        SELECT
            COUNT(DISTINCT order_id) AS order_count
        FROM ecommerce
        GROUP BY customer_unique_id
    )
)
ORDER BY total_orders DESC;
"""

pd.read_sql(query, conn)

                    customer_unique_id  total_orders
0     8d50f5eadf50201ccdcedfb9e2ac8455            17
1     3e43e6105506432c953e165fb2acf44c             9
2     ca77025e7201e3b30c44b472ff346268             7
3     6469f99c1f9dfae7733b25662e7f1782             7
4     1b6c7548a2a1f9037c1fd3ddfed95f33             7
...                                ...           ...
2992  00a39521eb40f7012db50455bf083460             2
2993  0058f300f57d7b93c477a131a59b36c3             2
2994  004b45ec5c64187465168251cd1c9c2f             2
2995  004288347e5e88a27ded2bb23747066c             2
2996  00172711b30d52eea8b313a7f2cced02             2

[2997 rows x 2 columns]

# 9. Common Table Expressions (CTEs)

A Common Table Expression (CTE) is a temporary named result set created using the `WITH` clause. It simplifies complex SQL queries by breaking them into smaller, more readable parts.

CTEs improve query readability, maintainability, and debugging. They are widely used in business reporting, data analysis, and ETL processes.

In [79]:
query = """
WITH state_revenue AS
(
    SELECT
        customer_state,
        ROUND(SUM(price + freight_value),2) AS total_revenue
    FROM ecommerce
    GROUP BY customer_state
)

SELECT *
FROM state_revenue
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conn)

   customer_state  total_revenue
0              SP     6234533.82
1              RJ     2247128.32
2              MG     1928571.09
3              RS      934286.75
4              PR      832059.40
5              BA      650220.38
6              SC      632514.14
7              GO      368997.61
8              DF      367750.15
9              ES      336438.54
10             PE      334467.37
11             CE      290599.59
12             PA      224924.18
13             MT      203768.97
14             MA      155510.26
15             PB      151482.79
16             MS      141346.92
17             RN      114747.31
18             PI      114729.56
19             AL       99781.70
20             SE       75495.89
21             TO       69702.51
22             RO       58681.50
23             AM       28549.04
24             AC       20861.50
25             AP       16517.39
26             RR       10064.62

In [80]:
query = """
WITH customer_spending AS
(
    SELECT
        customer_unique_id,
        MAX(customer_total_spending) AS total_spending
    FROM ecommerce
    GROUP BY customer_unique_id
)

SELECT *
FROM customer_spending
ORDER BY total_spending DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                 customer_unique_id  total_spending
0  8af7ac63b2efbcbd88e5b11505e8098a       385169.59
1  85963fd37bfd387aa6d915d8a1065486       253278.72
2  9a736b248f67d166d2fbb006bcb877c3       223818.84
3  c4b224d2c784bae11ae98b6ae9f2454c       166671.00
4  6fbc7cdadbb522125f4b27ae9dee4060       148544.28
5  f9ae226291893fda10af7965268fb7f6       134091.27
6  0a0a92112bd4c708ca5fde585afaa872       109312.64
7  301d1ce5a76b7e1bc47e5115bf5eb6ba       103791.80
8  db1af3fd6b23ac3873ef02619d548f9c        94815.36
9  be74c431147c32ab2d7c7cef5e4a995f        70386.54

In [81]:
query = """
WITH delivery_summary AS
(
    SELECT
        customer_state,
        ROUND(AVG(delivery_days),2) AS avg_delivery_days
    FROM ecommerce
    GROUP BY customer_state
)

SELECT *
FROM delivery_summary
ORDER BY avg_delivery_days ASC;
"""

pd.read_sql(query, conn)

   customer_state  avg_delivery_days
0              SP               8.27
1              MG              11.50
2              PR              11.52
3              DF              12.50
4              SC              14.51
5              RS              14.70
6              RJ              14.77
7              GO              14.90
8              MS              15.06
9              ES              15.24
10             TO              16.66
11             MT              17.52
12             PE              17.77
13             BA              18.73
14             PI              18.89
15             RN              19.18
16             RO              19.23
17             PB              20.11
18             AC              20.17
19             CE              20.34
20             SE              20.89
21             MA              21.19
22             PA              23.27
23             AL              24.13
24             AM              26.06
25             AP              27.66
26             RR              27.83

In [82]:
query = """
WITH category_revenue AS
(
    SELECT
        product_category_name,
        ROUND(SUM(price + freight_value),2) AS total_revenue
    FROM ecommerce
    GROUP BY product_category_name
)

SELECT *
FROM category_revenue
ORDER BY total_revenue DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

    product_category_name  total_revenue
0            beleza_saude     1491397.76
1      relogios_presentes     1358845.59
2         cama_mesa_banho     1327662.02
3           esporte_lazer     1205197.85
4  informatica_acessorios     1104362.03
5        moveis_decoracao      955367.22
6   utilidades_domesticas      823623.50
7              cool_stuff      752702.21
8              automotivo      714431.95
9      ferramentas_jardim      625387.31

In [83]:
query = """
WITH state_revenue AS
(
    SELECT
        customer_state,
        SUM(price + freight_value) AS total_revenue
    FROM ecommerce
    GROUP BY customer_state
)

SELECT
    customer_state,
    ROUND(total_revenue,2) AS total_revenue
FROM state_revenue
WHERE total_revenue >
(
    SELECT AVG(total_revenue)
    FROM state_revenue
)
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conn)

  customer_state  total_revenue
0             SP     6234533.82
1             RJ     2247128.32
2             MG     1928571.09
3             RS      934286.75
4             PR      832059.40
5             BA      650220.38
6             SC      632514.14

In [84]:
query = """
WITH payment_summary AS
(
    SELECT
        payment_type,
        ROUND(AVG(order_value),2) AS avg_order_value
    FROM ecommerce
    GROUP BY payment_type
)

SELECT *
FROM payment_summary
ORDER BY avg_order_value DESC;
"""

pd.read_sql(query, conn)

  payment_type  avg_order_value
0      voucher           667.66
1  credit_card           194.03
2       boleto           178.22
3   debit_card           150.56
4         None           143.46
5  not_defined             0.00

# 10. Window Functions

Window functions perform calculations across a set of rows related to the current row without collapsing the results into a single row.

Unlike `GROUP BY`, window functions return a value for every row while still allowing aggregate calculations.

Window functions are widely used for:
- Ranking
- Running totals
- Moving averages
- Previous and next row analysis
- Top-N analysis

In [86]:
query = """
SELECT
    order_id,
    order_value,
    ROW_NUMBER() OVER(
        ORDER BY order_value DESC
    ) AS row_number
FROM ecommerce
LIMIT 10;
"""

pd.read_sql(query, conn)

                           order_id  order_value  row_number
0  03caa2c082116e1d31e67e9ae3700499     13664.08           1
1  03caa2c082116e1d31e67e9ae3700499     13664.08           2
2  03caa2c082116e1d31e67e9ae3700499     13664.08           3
3  03caa2c082116e1d31e67e9ae3700499     13664.08           4
4  03caa2c082116e1d31e67e9ae3700499     13664.08           5
5  03caa2c082116e1d31e67e9ae3700499     13664.08           6
6  03caa2c082116e1d31e67e9ae3700499     13664.08           7
7  03caa2c082116e1d31e67e9ae3700499     13664.08           8
8  fa65dad1b0e818e3ccc5cb0e39231352     13281.71           9
9  fa65dad1b0e818e3ccc5cb0e39231352     13281.71          10

In [87]:
query = """
SELECT
    order_id,
    order_value,
    RANK() OVER(
        ORDER BY order_value DESC
    ) AS order_rank
FROM ecommerce
LIMIT 10;
"""

pd.read_sql(query, conn)

                           order_id  order_value  order_rank
0  03caa2c082116e1d31e67e9ae3700499     13664.08           1
1  03caa2c082116e1d31e67e9ae3700499     13664.08           1
2  03caa2c082116e1d31e67e9ae3700499     13664.08           1
3  03caa2c082116e1d31e67e9ae3700499     13664.08           1
4  03caa2c082116e1d31e67e9ae3700499     13664.08           1
5  03caa2c082116e1d31e67e9ae3700499     13664.08           1
6  03caa2c082116e1d31e67e9ae3700499     13664.08           1
7  03caa2c082116e1d31e67e9ae3700499     13664.08           1
8  fa65dad1b0e818e3ccc5cb0e39231352     13281.71           9
9  fa65dad1b0e818e3ccc5cb0e39231352     13281.71           9

In [88]:
query = """
SELECT
    order_id,
    order_value,
    DENSE_RANK() OVER(
        ORDER BY order_value DESC
    ) AS dense_rank
FROM ecommerce
LIMIT 10;
"""

pd.read_sql(query, conn)

                           order_id  order_value  dense_rank
0  03caa2c082116e1d31e67e9ae3700499     13664.08           1
1  03caa2c082116e1d31e67e9ae3700499     13664.08           1
2  03caa2c082116e1d31e67e9ae3700499     13664.08           1
3  03caa2c082116e1d31e67e9ae3700499     13664.08           1
4  03caa2c082116e1d31e67e9ae3700499     13664.08           1
5  03caa2c082116e1d31e67e9ae3700499     13664.08           1
6  03caa2c082116e1d31e67e9ae3700499     13664.08           1
7  03caa2c082116e1d31e67e9ae3700499     13664.08           1
8  fa65dad1b0e818e3ccc5cb0e39231352     13281.71           2
9  fa65dad1b0e818e3ccc5cb0e39231352     13281.71           2

In [89]:
query = """
SELECT
    customer_state,
    order_id,
    order_value,
    RANK() OVER(
        PARTITION BY customer_state
        ORDER BY order_value DESC
    ) AS state_rank
FROM ecommerce;
"""

pd.read_sql(query, conn).head(20)

   customer_state                          order_id  order_value  state_rank
0              AC  37fef9185066b091254533c2192edd72      1990.36           1
1              AC  37fef9185066b091254533c2192edd72      1990.36           1
2              AC  2bcf1f79964f8b4f4f62f19441601b1a      1251.70           3
3              AC  185e7ea81e4cf0fc1d2f4e8e38e8e7e3       905.93           4
4              AC  ad7d812f43f6308a7105fecab91fe3c1       861.26           5
5              AC  57be20dc5f786ed372add8e3f28be447       646.44           6
6              AC  57be20dc5f786ed372add8e3f28be447       646.44           6
7              AC  57be20dc5f786ed372add8e3f28be447       646.44           6
8              AC  57be20dc5f786ed372add8e3f28be447       646.44           6
9              AC  57be20dc5f786ed372add8e3f28be447       646.44           6
10             AC  57be20dc5f786ed372add8e3f28be447       646.44           6
11             AC  3c842261892c32fb5ce15222b72fa6e0       618.60          12
12             AC  ac4b7ecdaaa68d5c37e626e9a1f49005       595.49          13
13             AC  b8d8f5e99979f7cbf541344ae12c8cf4       591.88          14
14             AC  f5ac6a806078f4dfd6e72e601f8aa3ba       548.93          15
15             AC  c3ad507aba1f6b47354085e7e6bed0cf       467.08          16
16             AC  c3ad507aba1f6b47354085e7e6bed0cf       467.08          16
17             AC  c3ad507aba1f6b47354085e7e6bed0cf       467.08          16
18             AC  9bad44921c98e1f220a667504bcffb9e       448.30          19
19             AC  63a3eb68025b31c84a0bfca8a8b27ec3       446.18          20

In [90]:
query = """
SELECT
    order_purchase_timestamp,
    price,
    SUM(price) OVER(
        ORDER BY order_purchase_timestamp
    ) AS running_revenue
FROM ecommerce
LIMIT 20;
"""

pd.read_sql(query, conn)

   order_purchase_timestamp   price  running_revenue
0       2016-09-04 21:15:19   39.99            72.89
1       2016-09-04 21:15:19   32.90            72.89
2       2016-09-05 00:15:34   59.50           132.39
3       2016-09-13 15:24:19     NaN           132.39
4       2016-09-15 12:16:38   44.99           267.36
5       2016-09-15 12:16:38   44.99           267.36
6       2016-09-15 12:16:38   44.99           267.36
7       2016-10-02 22:07:52  100.00           367.36
8       2016-10-03 09:44:50   29.90           397.26
9       2016-10-03 16:56:50   21.90           419.16
10      2016-10-03 21:01:41   21.50           440.66
11      2016-10-03 21:13:36   36.49           477.15
12      2016-10-03 22:06:03  119.90           597.05
13      2016-10-03 22:31:31   29.99           627.04
14      2016-10-03 22:44:10  128.90           755.94
15      2016-10-03 22:51:30   74.90           830.84
16      2016-10-04 09:06:10   49.99           880.83
17      2016-10-04 09:16:33   32.49           913.32
18      2016-10-04 09:59:03   89.90          1003.22
19      2016-10-04 10:05:45     NaN          1003.22

In [91]:
query = """
SELECT
    order_purchase_timestamp,
    order_value,
    LAG(order_value) OVER(
        ORDER BY order_purchase_timestamp
    ) AS previous_order_value
FROM ecommerce
LIMIT 20;
"""

pd.read_sql(query, conn)

   order_purchase_timestamp  order_value  previous_order_value
0       2016-09-04 21:15:19       136.23                   NaN
1       2016-09-04 21:15:19       136.23                136.23
2       2016-09-05 00:15:34        75.06                136.23
3       2016-09-13 15:24:19         0.00                 75.06
4       2016-09-15 12:16:38       143.46                  0.00
5       2016-09-15 12:16:38       143.46                143.46
6       2016-09-15 12:16:38       143.46                143.46
7       2016-10-02 22:07:52       109.34                143.46
8       2016-10-03 09:44:50        45.46                109.34
9       2016-10-03 16:56:50        39.09                 45.46
10      2016-10-03 21:01:41        35.61                 39.09
11      2016-10-03 21:13:36        53.73                 35.61
12      2016-10-03 22:06:03       133.46                 53.73
13      2016-10-03 22:31:31        40.95                133.46
14      2016-10-03 22:44:10       154.57                 40.95
15      2016-10-03 22:51:30        92.27                154.57
16      2016-10-04 09:06:10        65.50                 92.27
17      2016-10-04 09:16:33        44.23                 65.50
18      2016-10-04 09:59:03       114.77                 44.23
19      2016-10-04 10:05:45         0.00                114.77

In [92]:
query = """
SELECT
    order_purchase_timestamp,
    order_value,
    LEAD(order_value) OVER(
        ORDER BY order_purchase_timestamp
    ) AS next_order_value
FROM ecommerce
LIMIT 20;
"""

pd.read_sql(query, conn)

   order_purchase_timestamp  order_value  next_order_value
0       2016-09-04 21:15:19       136.23            136.23
1       2016-09-04 21:15:19       136.23             75.06
2       2016-09-05 00:15:34        75.06              0.00
3       2016-09-13 15:24:19         0.00            143.46
4       2016-09-15 12:16:38       143.46            143.46
5       2016-09-15 12:16:38       143.46            143.46
6       2016-09-15 12:16:38       143.46            109.34
7       2016-10-02 22:07:52       109.34             45.46
8       2016-10-03 09:44:50        45.46             39.09
9       2016-10-03 16:56:50        39.09             35.61
10      2016-10-03 21:01:41        35.61             53.73
11      2016-10-03 21:13:36        53.73            133.46
12      2016-10-03 22:06:03       133.46             40.95
13      2016-10-03 22:31:31        40.95            154.57
14      2016-10-03 22:44:10       154.57             92.27
15      2016-10-03 22:51:30        92.27             65.50
16      2016-10-04 09:06:10        65.50             44.23
17      2016-10-04 09:16:33        44.23            114.77
18      2016-10-04 09:59:03       114.77              0.00
19      2016-10-04 10:05:45         0.00            237.45

In [93]:
query = """
SELECT
    customer_state,
    order_id,
    order_value,
    ROUND(
        AVG(order_value) OVER(
            PARTITION BY customer_state
        ),
        2
    ) AS state_average_order_value
FROM ecommerce;
"""

pd.read_sql(query, conn).head(20)

,customer_state,order_id,order_value,state_average_order_value
0,AC,d445a6e277eaa62900bc18d453d96d76,225.42,300.52
1,AC,cab041d8d606d6c9d3165da578795340,50.14,300.52
2,AC,1a9f85c859f73034acc85057b4899a8e,361.27,300.52
3,AC,0d4628fecf8a76472ac1da3ebef92072,316.19,300.52
4,AC,40aecb2022cf80ba1efc9b0ddf5cd690,82.42,300.52
5,AC,93dc7c78fb2b4efe25f1ed813f84992a,280.09,300.52
6,AC,62686dac3e596036e72fe0beb571e45e,312.02,300.52
7,AC,0fa05bb83efc10205ac8f4224f10c336,147.59,300.52
8,AC,b2345f8f3b34a4c0c28296057f032fb9,81.88,300.52
9,AC,52b5d9c64618868f5f1367c7934dbf1f,139.52,300.52
10,AC,ad7d812f43f6308a7105fecab91fe3c1,861.26,300.52
11,AC,d9644b981a4d023c5392dd06bfc8cdc0,55.28,300.52
12,AC,83d500e46a95c23dd67eb3cadbd1bd13,241.08,300.52
13,AC,a7abe735fa002a72636ab38fcac70330,62.92,300.52
14,AC,ce720cfa1cadab0ab4c19a956254d382,77.20,300.52
15,AC,0c956783114b7ac9633e16c494c191ce,141.32,300.52
16,AC,ddb4b2115723295bbe34444bbcb2c1d5,220.39,300.52
17,AC,f53fee7428c6bc090f954df111b6e0f0,318.30,300.52
18,AC,5f9023a84ef9e64c87bc7c1970da5680,100.91,300.52
19,AC,5b829c37201779df841d79b1875ca7ef,171.03,300.52

# 11. Business Case Studies

This section demonstrates how SQL can be used to solve real-world business problems using the engineered e-commerce dataset.

Each case study represents a common business question that a Data Analyst may be asked to answer. The solutions combine SQL concepts such as filtering, aggregation, grouping, CTEs, subqueries, and window functions.

In [95]:
query = """
SELECT
    customer_state,
    ROUND(SUM(price + freight_value),2) AS total_revenue
FROM ecommerce
GROUP BY customer_state
ORDER BY total_revenue DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

  customer_state  total_revenue
0             SP     6234533.82
1             RJ     2247128.32
2             MG     1928571.09
3             RS      934286.75
4             PR      832059.40
5             BA      650220.38
6             SC      632514.14
7             GO      368997.61
8             DF      367750.15
9             ES      336438.54

In [96]:
query = """
SELECT
    product_category_name,
    ROUND(SUM(price + freight_value),2) AS total_revenue
FROM ecommerce
GROUP BY product_category_name
ORDER BY total_revenue DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

    product_category_name  total_revenue
0            beleza_saude     1491397.76
1      relogios_presentes     1358845.59
2         cama_mesa_banho     1327662.02
3           esporte_lazer     1205197.85
4  informatica_acessorios     1104362.03
5        moveis_decoracao      955367.22
6   utilidades_domesticas      823623.50
7              cool_stuff      752702.21
8              automotivo      714431.95
9      ferramentas_jardim      625387.31

In [97]:
query = """
SELECT
    customer_unique_id,
    MAX(customer_total_spending) AS total_spending
FROM ecommerce
GROUP BY customer_unique_id
ORDER BY total_spending DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                 customer_unique_id  total_spending
0  8af7ac63b2efbcbd88e5b11505e8098a       385169.59
1  85963fd37bfd387aa6d915d8a1065486       253278.72
2  9a736b248f67d166d2fbb006bcb877c3       223818.84
3  c4b224d2c784bae11ae98b6ae9f2454c       166671.00
4  6fbc7cdadbb522125f4b27ae9dee4060       148544.28
5  f9ae226291893fda10af7965268fb7f6       134091.27
6  0a0a92112bd4c708ca5fde585afaa872       109312.64
7  301d1ce5a76b7e1bc47e5115bf5eb6ba       103791.80
8  db1af3fd6b23ac3873ef02619d548f9c        94815.36
9  be74c431147c32ab2d7c7cef5e4a995f        70386.54

In [98]:
query = """
SELECT
    purchase_year,
    purchase_month,
    ROUND(SUM(price + freight_value),2) AS monthly_revenue
FROM ecommerce
GROUP BY purchase_year, purchase_month
ORDER BY purchase_year, purchase_month;
"""

pd.read_sql(query, conn)

    purchase_year  purchase_month  monthly_revenue
0            2016               9           354.75
1            2016              10         58730.85
2            2016              12            19.62
3            2017               1        148030.11
4            2017               2        303648.31
5            2017               3        459778.64
6            2017               4        449707.81
7            2017               5        634762.22
8            2017               6        531052.06
9            2017               7        631341.57
10           2017               8        706168.95
11           2017               9        767325.70
12           2017              10        808911.33
13           2017              11       1232074.30
14           2017              12        898427.92
15           2018               1       1158742.84
16           2018               2       1039011.65
17           2018               3       1209080.30
18           2018               4       1201102.21
19           2018               5       1193204.98
20           2018               6       1075753.44
21           2018               7       1097939.54
22           2018               8       1038395.74
23           2018               9           166.46
24           2018              10              NaN

In [99]:
query = """
SELECT
    customer_state,
    ROUND(AVG(delivery_days),2) AS avg_delivery_days
FROM ecommerce
GROUP BY customer_state
ORDER BY avg_delivery_days;
"""

pd.read_sql(query, conn)

   customer_state  avg_delivery_days
0              SP               8.27
1              MG              11.50
2              PR              11.52
3              DF              12.50
4              SC              14.51
5              RS              14.70
6              RJ              14.77
7              GO              14.90
8              MS              15.06
9              ES              15.24
10             TO              16.66
11             MT              17.52
12             PE              17.77
13             BA              18.73
14             PI              18.89
15             RN              19.18
16             RO              19.23
17             PB              20.11
18             AC              20.17
19             CE              20.34
20             SE              20.89
21             MA              21.19
22             PA              23.27
23             AL              24.13
24             AM              26.06
25             AP              27.66
26             RR              27.83

In [100]:
query = """
SELECT
    payment_type,
    COUNT(DISTINCT order_id) AS total_orders
FROM ecommerce
GROUP BY payment_type
ORDER BY total_orders DESC;
"""

pd.read_sql(query, conn)

  payment_type  total_orders
0  credit_card         76505
1       boleto         19784
2      voucher          3866
3   debit_card          1528
4  not_defined             3
5         None             1

In [101]:
query = """
SELECT
    product_category_name,
    ROUND(AVG(review_score),2) AS average_review_score
FROM ecommerce
GROUP BY product_category_name
ORDER BY average_review_score DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                product_category_name  average_review_score
0                   cds_dvds_musicais                  4.64
1       fashion_roupa_infanto_juvenil                  4.50
2              livros_interesse_geral                  4.44
3                   livros_importados                  4.42
4                              flores                  4.42
5  construcao_ferramentas_ferramentas                  4.42
6                     livros_tecnicos                  4.38
7         portateis_casa_forno_e_cafe                  4.32
8                   alimentos_bebidas                  4.32
9                    malas_acessorios                  4.30

In [102]:
query = """
SELECT
    seller_id,
    COUNT(product_id) AS products_sold
FROM ecommerce
GROUP BY seller_id
ORDER BY products_sold DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                          seller_id  products_sold
0  4a3ca9315b744ce9f8e9374361493884           2155
1  6560211a19b47992c3666cc44a7e94c0           2130
2  1f50f920176fa81dab994f9023523100           2017
3  cc419e0650a3c5ba77189a1882b7556a           1893
4  da8622b14eb17ae2831f4ac5b9dab84a           1662
5  955fee9216a65b617aa5c0531780ce60           1530
6  1025f0e2d44d7041d6cf58b6550e0bfa           1477
7  7c67e1448b00f6e969d365cea6b010ab           1463
8  7a67c85e85bb2ce8582c35f2203ad736           1245
9  ea8482cd71df3c1969d7b9473ff13abc           1240

In [103]:
query = """
SELECT
    customer_state,
    COUNT(*) AS late_deliveries
FROM ecommerce
WHERE late_delivery = 1
GROUP BY customer_state
ORDER BY late_deliveries DESC;
"""

pd.read_sql(query, conn)

   customer_state  late_deliveries
0              SP             2758
1              RJ             1936
2              MG              723
3              BA              543
4              RS              435
5              SC              405
6              PR              281
7              ES              281
8              CE              226
9              PE              188
10             GO              188
11             DF              179
12             MA              166
13             PA              135
14             AL              109
15             MS               90
16             PI               88
17             PB               72
18             MT               71
19             RN               65
20             SE               61
21             TO               38
22             RO               11
23             AM                7
24             RR                5
25             AP                4
26             AC                3

In [104]:
query = """
SELECT
    product_id,
    product_category_name,
    price
FROM ecommerce
ORDER BY price DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

                         product_id  product_category_name   price
0  489ae2aa008f021502940f251d4cce7f  utilidades_domesticas  6735.0
1  69c590f7ffc7bf8db97190b6cb6ed62e                    pcs  6729.0
2  1bdf5e6731585cf01aa8169c7028d6ad                  artes  6499.0
3  a6492cc69376c469ab6f61d8f44de961        eletroportateis  4799.0
4  c3ed642d592594bb648ff4a04cee2747        eletroportateis  4690.0

# 📊 Summary

In this notebook, we performed SQL-based analysis on the engineered Olist E-commerce dataset using SQLite.

## SQL Concepts Covered

- Basic SQL Queries
- WHERE Clause
- ORDER BY
- Aggregate Functions
- GROUP BY
- HAVING
- CASE WHEN
- Subqueries
- Common Table Expressions (CTEs)
- Window Functions
- Business Case Studies

## Key Business Insights Generated

- Revenue by State
- Revenue by Product Category
- Customer Spending Analysis
- Delivery Performance
- Monthly Sales Trend
- Payment Method Analysis
- Customer Satisfaction
- Seller Performance
- Late Delivery Analysis

This notebook demonstrates practical SQL skills commonly used by Data Analysts for business reporting and decision-making.